# Generated by Django 4.1.2 on 2025-01-03 10:55

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Civil_Status",
            fields=[
                (
                    "nationality_id",
                    models.CharField(
                        max_length=20, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("full_name", models.CharField(max_length=200, null=True)),
                ("birth", models.DateField()),
                (
                    "gender",
                    models.CharField(
                        choices=[("Male", "Male"), ("Female", "Female")],
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True, default="avatar.jpg", null=True, upload_to=""
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Disease",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("ADMIN", "Admin"),
                            ("HOSPITAL", "Hospital"),
                            ("PATIENT", "Patient"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to.",
                        related_name="custom_user_set",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="custom_user_set",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Hospital",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("api.user",),
            managers=[
                ("hospital", django.db.models.manager.Manager()),
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Patient",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("api.user",),
            managers=[
                ("patient", django.db.models.manager.Manager()),
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Prescription",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.TextField()),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("Heart Disease", "Heart Disease"),
                            ("Skin Care", "Skin Care"),
                            ("Diabetes Disease", "Diabetes Disease"),
                        ],
                        max_length=200,
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("note", models.CharField(blank=True, max_length=1000, null=True)),
                (
                    "patient",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="patient",
                        to="api.patient",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PatientProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone", models.CharField(max_length=20)),
                ("date_joined", models.DateField(auto_now_add=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "photo",
                    models.ImageField(
                        blank=True, default="avatar.jpg", null=True, upload_to=""
                    ),
                ),
                (
                    "civil_status",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.civil_status",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="api.patient"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Patient_Disease",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("date", models.DateTimeField(auto_now_add=True)),
                (
                    "disease",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.disease",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.patient",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Medical_Examination",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("Biopsy", "Biopsy"),
                            ("Colonoscopy", "Colonoscopy"),
                            ("CT scan", "CT scan"),
                            ("Electrocardiogram (ECG)", "Electrocardiogram (ECG)"),
                            (
                                "Electroencephalogram (EEG)",
                                "Electroencephalogram (EEG)",
                            ),
                            ("Gastroscopy", "Gastroscopy"),
                            ("Eye tests", "Eye tests"),
                            ("Hearing test", "Hearing test"),
                            ("MRI scan", "MRI scan"),
                            ("PET scan", "PET scan"),
                            ("Ultrasound", "Ultrasound"),
                            ("X-rays", "X-rays"),
                        ],
                        max_length=200,
                    ),
                ),
                ("report", models.CharField(blank=True, max_length=1000, null=True)),
                ("date", models.DateField(auto_now_add=True, null=True)),
                (
                    "result",
                    models.FileField(
                        upload_to="C:\\Users\\MBaji\\django\\healthcare\\static/media"
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="medical_examination_patient",
                        to="api.patient",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Kin",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("full_name", models.CharField(max_length=200)),
                ("address", models.CharField(max_length=1000, null=True)),
                ("phone", models.CharField(max_length=20)),
                ("email", models.EmailField(max_length=200, null=True, unique=True)),
                (
                    "relationship",
                    models.CharField(
                        choices=[
                            ("Father", "Father"),
                            ("Mother", "Mother"),
                            ("Husband", "Husband"),
                            ("Wife", "Wife"),
                            ("Son", "Son"),
                            ("Daughter", "Dauther"),
                            ("Brother", "Father"),
                            ("Sister", "Sister"),
                            ("Uncle", "Uncle"),
                            ("aunt", "aunt"),
                            ("Grandfather", "Grandfather"),
                            ("grandmother", "grandmother"),
                            ("Step Father", "Step Father"),
                            ("Step Mother", "Step Mother"),
                        ],
                        max_length=200,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="kin_patient",
                        to="api.patient",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HospitalProfile",
            fields=[
                (
                    "hospital_id",
                    models.IntegerField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("logo", models.ImageField(blank=True, null=True, upload_to="")),
                ("is_active", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("date_joined", models.DateField(auto_now_add=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="api.hospital"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Hospital_Patient",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("date", models.DateTimeField(auto_now_add=True)),
                (
                    "hospital",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="hospital_for_patient",
                        to="api.hospital",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="patient_in_hospital",
                        to="api.patient",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Basic_Health_State",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("heart_rate", models.IntegerField(default=0)),
                ("oxygen_saturation", models.IntegerField(default=0)),
                ("body_temperature", models.IntegerField(default=0)),
                ("glucose_level", models.IntegerField(default=0)),
                ("date", models.DateTimeField(auto_now_add=True)),
                (
                    "patient",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="basic_health_state_patient",
                        to="api.patient",
                    ),
                ),
            ],
        ),
    ]
